name: Testing Github Actions
run-name: ${{github.actor}} is Running pipeline

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the setup job"

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: "This is the build job"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: "This is the test job"