name: Testing Github Actions
run-name: ${{github.actor}} is Running pipeline

on: [push]

jobs:
  Testing-Pipeline:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Retrieve secret
        env:
          secret_name: ${{secrets.SECRET_NAME}}
        run: echo "This is the secret_name $secret_name